# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  projeto_java_nativo:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Instalando a JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Compilar o Java
      run: javac -cp src src/Main.java
    
    - name: Executando o Projeto
      run: |
        cd src
        java Main 
